### ISSUE TITLE
ERROR: subtransaction logged without previous top-level txn record

### ISSUE THREAD

**Issue by igouss** [eulerto/wal2json#157]
Hello,

have errors like this for some databases.

```
AbstractReplicationStream ERROR --- wal2json failed errorType=WAL2JSON_SLOT 
org.postgresql.util.PSQLException: ERROR: subtransaction logged without previous top-level txn record
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1155)
	at org.postgresql.core.v3.QueryExecutorImpl.readFromCopy(QueryExecutorImpl.java:1062)
	at org.postgresql.core.v3.CopyDualImpl.readFromCopy(CopyDualImpl.java:37)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.receiveNextData(V3PGReplicationStream.java:158)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.readInternal(V3PGReplicationStream.java:123)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.readPending(V3PGReplicationStream.java:80)
```

```
    @Override
    public ByteBuffer getStreamByteBuffer(@NonNull PGReplicationStream pgReplicationStream) throws SQLException {

        ByteBuffer msg = pgReplicationStream.readPending();
```

Do you know why this happens and if wal2json can be modified to not send such data?
I don't have reproduction steps for this.

**Comment by eulerto** [comment]
What is your postgres version? This message indicates a bug in logical decoding.

**Comment by quentinbricard** [comment]
Postgres version is 10.12

**Comment by igouss** [comment]
We are running older version of the plugin, I'll try to get new version of wal2json installed, to see if it would fix the issue.

**Comment by igouss** [comment]
```
testdb=# select pg_logical_slot_get_changes('cdc_testdb', NULL, 1);
ERROR:  subtransaction logged without previous top-level txn record
```

**Comment by eulerto** [comment]
Do you have a test case? Did you advance LSN position in replication slot `cdc_testdb`? There seems to be a few bugs ([last one](https://www.postgresql.org/message-id/AB5978B2-1772-4FEE-A245-74C91704ECB0%40amazon.com)) around this code on postgres.

**Comment by igouss** [comment]
I'm not sure how but we used https://github.com/bahaa/wal2json.git 11f08a3 skip-empty-xacts.
I'll close this ticket because of that.
